name: tumble_puzzle
description: A normal slide puzzle, just like in reality the first thing you do is break the frame so that you can organize the blocks as you wish.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: 3.5.4
  flutter: 3.24.5

dependencies:
  collection: 1.18.0
  flame: 1.22.0
  flame_forge2d: 0.18.2+3
  flutter:
    sdk: flutter
  flutter_linkify: 6.0.0
  flutter_riverpod: 2.6.1
  google_fonts: 6.2.1
  url_launcher: 6.3.1

dev_dependencies:
  flame_lint: 1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
